language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: firebase
  token:
    secure: "G5soKIhoqVXkXBV3KSCu/7dvfg1Z36IdzuvLfORoG0kxVWaJs5SBIzK/H4hiw/ARxmCGJ1TgWhIjQbgOHw38e3xecBOOZrTodiIcsbs7BaFykT1zXLsOdNEp5Fv/skJyjTGGuTJksQMYmCqJHsyQF+hrgI6s2SnqxsSihFz1BfXLhWVmPD8d6SO32qIyODKFWAvKKljLg0YxQYK/99nZ1dHbdaYN+Xfv9t9oTlkpMlkZ3bmSt3rwjcRR96fPk/W064mTEYVwzBtY09jA1xyRNQDzokfL7lAjDfurTXb0utHry9X5nUXoIAUJqU7Xe/OGyzErgWmrZI1dOI7ejClNNAzaeca3Q0uXYpNaS+BwEMuSuz9GjbspsY3lfBRJfND7lnyrNFBx6uZ2QLcK471zwUz0KnarvOi61c0W7hSeY1qiIyVWH7SEFa85SlqTTdW8ZtzFIneV7HPqi5jyS+ockc8RBJfu183w3aQkvIaxIX0F6Vm8thHkwS+/fY7Z/OAPgJ/0zNvRgxbc8kVFKJccIgxMTRYqB2C0u/64yHW74+awT+FnLyYikh78l81tJ8ZQ8AUBE+YBvJYnjEBfOfJXJ/Lcufe+rVGQmJ8sTl5/dk4Ee7FnlLTbfIgZkobJ+03f0dH+a89G7uN7j5AElQ5vKdVsw5d80xETSr4AtUfXDVo="
  skip_cleanup: true
on:
  branch: master
