language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before_script:
  - npm install firebase-tools -g
  - npm install
script:
  - npm test
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
on:
  branch: master
